# Generated by Django 4.2.29 on 2026-04-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
