# Generated by Django 4.2.29 on 2026-04-25 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '__first__'),
        ('bookings', '0003_delete_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=True)),
                ('booking_notifications', models.CharField(choices=[('in_app', 'In-App Only'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], default='in_app', max_length=20)),
                ('payment_notifications', models.CharField(choices=[('in_app', 'In-App Only'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], default='email', max_length=20)),
                ('promotional_notifications', models.CharField(choices=[('in_app', 'In-App Only'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], default='in_app', max_length=20)),
                ('system_notifications', models.CharField(choices=[('in_app', 'In-App Only'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], default='email', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_role', models.CharField(choices=[('customer', 'Customer'), ('provider', 'Service Provider'), ('admin', 'Admin')], max_length=20)),
                ('notification_type', models.CharField(choices=[('admin_user_registration', 'New User Registration'), ('admin_provider_registration', 'New Provider Registration'), ('admin_provider_verification', 'Provider Verification Request'), ('admin_user_complaint', 'User Complaint Filed'), ('admin_payment_failed', 'Payment Failure Alert'), ('admin_system_alert', 'System Alert'), ('admin_support_ticket', 'New Support Ticket'), ('admin_content_flagged', 'Content Flagged for Review'), ('admin_bulk_operation', 'Bulk Operation Completed'), ('user_registration_success', 'Registration Successful'), ('user_booking_confirmed', 'Booking Confirmed'), ('user_booking_updated', 'Booking Updated'), ('user_booking_cancelled', 'Booking Cancelled'), ('user_payment_success', 'Payment Successful'), ('user_payment_failed', 'Payment Failed'), ('user_provider_response', 'Provider Response'), ('user_support_update', 'Support Ticket Update'), ('user_promotional', 'Promotional Offer'), ('user_reminder', 'Reminder Alert'), ('user_account_change', 'Account Change'), ('provider_new_booking', 'New Booking Received'), ('provider_booking_cancelled', 'Booking Cancelled'), ('provider_new_review', 'New Review Received'), ('provider_payment_received', 'Payment Received'), ('provider_payout_processed', 'Payout Processed'), ('provider_account_approved', 'Account Approved'), ('provider_account_rejected', 'Account Rejected'), ('provider_profile_flagged', 'Profile Flagged'), ('provider_subscription_reminder', 'Subscription Reminder'), ('provider_new_message', 'New Message from User')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('is_email_sent', models.BooleanField(default=False)),
                ('is_sms_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.booking')),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient_role', 'is_read'], name='notificatio_recipie_6e712a_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
