import React, { useState, useEffect } from 'react';
import API from '../../api';

export default function AdminSettings() {
  const [activeTab, setActiveTab] = useState('2fa');
  const [qrCode, setQrCode] = useState('');
  const [secret, setSecret] = useState('');
  const [totpCode, setTotpCode] = useState('');
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');

  const setup2FA = async () => {
    try {
      const res = await API.setup2FA();
      setQrCode(res.data.qr_code);
      setSecret(res.data.secret);
    } catch (err) {
      setError('Failed to setup 2FA');
    }
  };

  const verify2FA = async () => {
    setMessage(''); setError('');
    try {
      const res = await API.verifySetup2FA({ totp_code: totpCode });
      setMessage(res.data.message);
      setQrCode(''); // hide QR code after success
    } catch (err) {
      setError(err.response?.data?.error || 'Invalid code');
    }
  };

  return (
    <div>
      <h1 className="text-2xl font-bold text-gray-800 mb-6">Settings</h1>
      
      <div className="bg-white rounded-xl shadow-sm border border-slate-200">
        <div className="border-b border-slate-200">
          <nav className="flex space-x-8 px-6" aria-label="Tabs">
            <button 
              className={`py-4 px-1 border-b-2 font-medium text-sm ${activeTab === '2fa' ? 'border-blue-500 text-blue-600' : 'border-transparent text-slate-500 hover:text-slate-700 hover:border-slate-300'}`}
              onClick={() => setActiveTab('2fa')}
            >
              Two-Factor Authentication (2FA)
            </button>
          </nav>
        </div>

        <div className="p-6">
          {activeTab === '2fa' && (
            <div className="max-w-md">
              <h3 className="text-lg font-medium text-gray-900 mb-4">Protect Your Account</h3>
              <p className="text-sm text-gray-500 mb-6">Add an extra layer of security to your admin account by enabling two-factor authentication.</p>
              
              {error && <div className="p-3 mb-4 text-sm text-red-700 bg-red-100 rounded-lg">{error}</div>}
              {message && <div className="p-3 mb-4 text-sm text-green-700 bg-green-100 rounded-lg">{message}</div>}

              {!qrCode ? (
                <button onClick={setup2FA} className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors">
                  Setup 2FA
                </button>
              ) : (
                <div className="border rounded-lg p-4 bg-slate-50">
                  <p className="text-sm font-medium mb-2">1. Scan this QR code with your Authenticator app</p>
                  <div className="bg-white p-2 inline-block rounded mb-4 shadow-sm">
                    <img src={qrCode} alt="2FA QR Code" className="w-48 h-48" />
                  </div>
                  
                  <p className="text-sm text-gray-500 mb-4">Or enter this code manually: <span className="font-mono font-bold bg-gray-200 px-1 rounded">{secret}</span></p>
                  
                  <p className="text-sm font-medium mb-2">2. Enter the 6-digit code generated by the app</p>
                  <div className="flex gap-2">
                    <input 
                      type="text" 
                      value={totpCode} 
                      onChange={(e) => setTotpCode(e.target.value)}
                      placeholder="123456" 
                      className="border rounded px-3 py-2 flex-1"
                      maxLength={6}
                    />
                    <button onClick={verify2FA} className="bg-green-600 text-white px-4 py-2 rounded hover:bg-green-700">
                      Verify & Enable
                    </button>
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
