# Generated by Django 4.2.30 on 2026-04-29 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_payment_id',
            new_name='stripe_charge_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_order_id',
            new_name='stripe_payment_intent_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_signature',
            new_name='stripe_signature',
        ),
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='razorpay_response',
            new_name='stripe_response',
        ),
        migrations.RenameField(
            model_name='payout',
            old_name='razorpay_payout_id',
            new_name='stripe_payout_id',
        ),
        migrations.RenameField(
            model_name='payout',
            old_name='razorpay_transfer_id',
            new_name='stripe_transfer_id',
        ),
        migrations.RenameField(
            model_name='providerbankaccount',
            old_name='razorpay_contact_id',
            new_name='stripe_account_id',
        ),
        migrations.RenameField(
            model_name='providerbankaccount',
            old_name='razorpay_fund_account_id',
            new_name='stripe_external_account_id',
        ),
        migrations.RenameField(
            model_name='refund',
            old_name='razorpay_refund_id',
            new_name='stripe_refund_id',
        ),
    ]
