# Generated by Django 4.2.30 on 2026-04-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_razorpay_payment_id_payment_stripe_charge_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_charge_id',
            new_name='razorpay_order_id',
        ),
        migrations.RenameField(
            model_name='payout',
            old_name='stripe_payout_id',
            new_name='razorpay_payout_id',
        ),
        migrations.RenameField(
            model_name='payout',
            old_name='stripe_transfer_id',
            new_name='razorpay_transfer_id',
        ),
        migrations.RenameField(
            model_name='providerbankaccount',
            old_name='stripe_account_id',
            new_name='razorpay_contact_id',
        ),
        migrations.RenameField(
            model_name='providerbankaccount',
            old_name='stripe_external_account_id',
            new_name='razorpay_fund_account_id',
        ),
        migrations.RenameField(
            model_name='refund',
            old_name='stripe_refund_id',
            new_name='razorpay_refund_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_signature',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='stripe_response',
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='razorpay_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
